[project]
name = "pdf-to-speech"
version = "0.1.0"
description = "Text to speech using elevenlabs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "elevenlabs>=2.21.0",
    "pypdf>=6.1.3",
    "python-dotenv>=1.2.1",
    "streamlit>=1.51.0",
    "streamlit-pdf>=1.0.8",
]
